### ISSUE TITLE
iptv-checker -o Erro

### ISSUE THREAD

**Issue by KomuSei** [freearhey/iptv-checker#2]
iptv-checker -o
internal/fs/utils.js:525
    throw new ERR_INVALID_ARG_TYPE(propName, ['string', 'Buffer', 'URL'], path);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL. Received type boolean
    at Object.mkdirSync (fs.js:815:10)
    at Object.<anonymous> (/usr/lib/node_modules/iptv-checker/src/index.js:42:6)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'ERR_INVALID_ARG_TYPE'
}

and also

iptv-checker -o /www/wwwroot/sample
(node:1307) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL. Received type object
    at Object.openSync (fs.js:432:10)
    at Object.readFileSync (fs.js:342:35)
    at readFile (/usr/lib/node_modules/iptv-checker/src/helper.js:15:13)
    at Object.parsePlaylist (/usr/lib/node_modules/iptv-checker/src/helper.js:19:19)
    at init (/usr/lib/node_modules/iptv-checker/src/index.js:63:25)
    at Object.<anonymous> (/usr/lib/node_modules/iptv-checker/src/index.js:57:1)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
(node:1307) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1307) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by freearhey** [comment]
For the script to work it is also necessary to specify the path to the playlist which should be checked:

```sh
iptv-checker /path/to/playlist.m3u -o /www/wwwroot/sample
```

**Comment by KomuSei** [comment]
> For the script to work it is also necessary to specify the path to the playlist which should be checked:
> 
> ```shell
> iptv-checker /path/to/playlist.m3u -o /www/wwwroot/sample
> ```
This really works good, thanks.

And there's some links were checked to offline, but they are actually online.
sample: http://pili-live-hdl.qhmywl.com:80/dsdtv/4677cf6625ce01b236bbb58f99094d51.m3u8

when i ping "pili-live-hdl.qhmywl.com", i got information like this:
正在 Ping pili-live-hdl.qhmywl.com.hdlv4.pilidns.com [1.1.1.1] 具有 32 字节的数据:
来自 1.1.1.1 的回复: 字节=32 时间=31ms TTL=58
来自 1.1.1.1 的回复: 字节=32 时间=32ms TTL=58
来自 1.1.1.1 的回复: 字节=32 时间=28ms TTL=58
来自 1.1.1.1 的回复: 字节=32 时间=28ms TTL=58

1.1.1.1 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 4，丢失 = 0 (0% 丢失)，
往返行程的估计时间(以毫秒为单位):
    最短 = 28ms，最长 = 32ms，平均 = 29ms

**Comment by freearhey** [comment]
I don't know exactly what the problem is, but this stream doesn't work in VLC player either.

**Comment by teiken100** [comment]
Καλησπέρα μπορείς να μου πεις αν μπωρο να δω ελληνικα κανάλια.οτε.νοβα;στο iptv με κοδικο
