### ISSUE TITLE
async function init()  in crontab

### ISSUE THREAD

**Issue by KomuSei** [freearhey/iptv-checker#4]
when i use crontab, it failed, but in normal station, it succeed

/usr/lib/node_modules/iptv-checker/src/index.js:59
async function init() 
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)

**Comment by freearhey** [comment]
Could you specify which version of Node.js you are using?

**Comment by KomuSei** [comment]
> Could you specify which version of Node.js you are using?

Node.js: V13.6.0
npm: V6.13.4

**Comment by freearhey** [comment]
And crontab works in the same environment?
